#source: /data/test_data/old_polar2grid_data/input/conus_day/{GITCO,GMTCO,SVM,SVI}*.h5
#command: polar2grid.sh viirs_sdr gtiff -f
#output: /data/users/kkolman/integration_tests/expected_test_output/conus_day

base_test_dir: /data
tests: 
  - source_dir: test_data/old_polar2grid_data/input/conus_day/{GITCO,GMTCO,SVM,SVI}*.h5
    command: polar2grid.sh viirs_sdr gtiff -f
    expected_dir: users/kkolman/integration_tests/expected_test_output/conus_day/viirssdr_to_gtiff
 # - source_dir: /data/test_data/old_polar2grid_data/polar2grid_test/modis/input  
 #   command: polar2gri
 #   expected_dir: 
 # - source_dir: 
 #   command: 
 #   expected_dir: 
